### PR TITLE
Adding 200m structures to biopandas

### PR DESCRIPTION
**Pull request by a-r-j**
Small update to support AF2 v3.

Very high structure:code ratio in this PR 😁

### CODE REVIEW

**Comment by rasbt** [comment]
Thanks a lot for the update!

**Comment by a-r-j** [comment]
It looks like tests are failing due to metadata changes in the local AF2 pdb/mmcif files. I'll fix this up.

**Comment by rasbt** [comment]
Thanks! So it looks like they also updated the previous alphafold-v2 structures? If that's just the meta-data, theoretically we could also just check for Atom entries. Otherwise, I am not sure whether we would have to update the check every few months or so 😅

**Comment by a-r-j** [comment]
It looks like it was just metadata. They just changed the date in the PDB file. In the mmCIF there were more changes but coords are unaffected. I added another block to test for the latest release but updated the old test to make sure everything works nicely with retrieving structures from previous releases too.

**Comment by rasbt** [comment]
Awesome, thanks!

**Pull request merged**
